package FilterApp;


/**
* FilterApp/FilterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/FilterApp.idl
* miércoles 12 de mayo de 2021 21H56' CEST
*/

abstract public class FilterHelper
{
  private static String  _id = "IDL:FilterApp/Filter:1.0";

  public static void insert (org.omg.CORBA.Any a, FilterApp.Filter that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FilterApp.Filter extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FilterApp.FilterHelper.id (), "Filter");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FilterApp.Filter read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FilterStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FilterApp.Filter value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FilterApp.Filter narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FilterApp.Filter)
      return (FilterApp.Filter)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FilterApp._FilterStub stub = new FilterApp._FilterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FilterApp.Filter unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FilterApp.Filter)
      return (FilterApp.Filter)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FilterApp._FilterStub stub = new FilterApp._FilterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
