package FilterApp;


/**
* FilterApp/FilterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/FilterApp.idl
* miércoles 12 de mayo de 2021 21H56' CEST
*/

public interface FilterOperations 
{
  String getFilterImage (String path, int filter);
  void shutdown ();
} // interface FilterOperations
