package FilterApp;


/**
* FilterApp/Filter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/FilterApp.idl
* miércoles 12 de mayo de 2021 21H56' CEST
*/

public interface Filter extends FilterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Filter
